### ISSUE TITLE
Add README to the project's metadata

### ISSUE THREAD

**Issue by oleg-nenashev** [tyrjola/robotframework-wiremock#12]
### Summary

Currently the documentation is not published to PyPi. It would be nice to have it included, see the guidelines below

### References

https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by TomerPacific** [comment]
Hi @oleg-nenashev, I'd like to help here.

**Comment by TomerPacific** [comment]
@oleg-nenashev - Created a [PR](https://github.com/wiremock/robotframework-wiremock/pull/15)

**Comment by oleg-nenashev** [comment]
Thanks! Will merge and release the module

**Comment by oleg-nenashev** [comment]
Thanks @TomerPacific, It works! https://pypi.org/project/wiremock/

**Comment by TomerPacific** [comment]
@oleg-nenashev - Great to hear. I'm waiting for your feedback on this issue -> https://github.com/wiremock/wiremock.org/issues/210.
It would be appreciated if you could give it a look.

**Comment by oleg-nenashev** [comment]
It is not needed, because the repository is marked for Hacktoberfest. But will add it so that there is no timeout
