### ISSUE TITLE
Adopting the repository in https://github.com/wiremock ?

### ISSUE THREAD

**Issue by oleg-nenashev** [tyrjola/robotframework-wiremock#5]
Hi @tyrjola . My name is Oleg Nenashev. In April I joined the WireMock team to help with growing the WireMock community and its open source ecosystem. The Python ecosystem is one of my priorities for the next months, and I would be happy to improve the Robot Framework integration after using it quite a lot at my previous jobs 

We have recently release a new version of [Python WireMock](https://github.com/wiremock/python-wiremock) that introduced the Testcontainers module and also refreshed the documentation & Co. I would be interested to add integrations to the Robot Framework library so that it becomes more flexible and feature rich.

Are you still interested in this project? And, regardless of the answer, would you be potentially interested in transferring it to https://github.com/wiremock so that we could make it a full part of the community governance and attract more contributor? If you're interested to keep maintaining it, it would be awesome too

**Comment by tyrjola** [comment]
Hi @oleg-nenashev !

I'd be happy to hand it over, especially to the Wiremock team. :) I'll also transfer the related PyPI repo to you guys in case you'd like to keep the same name (that would probably make it easier for existing users as well).

I suppose I'm not able to initiate a transfer request since it would be transfered to an organization to which I do not have permissions, but please let me know how you'd like to proceed with this.

**Comment by oleg-nenashev** [comment]
Hi, thanks a lot for your response! I accepted the pypi transfer. For
GitHub, I might need to add you as a collaborator to the organization if
the transfer request does not work.

**Comment by oleg-nenashev** [comment]
@tyrjola Invited you to https://github.com/wiremock so you can definitely do the transfer

**Comment by tyrjola** [comment]
Thanks @oleg-nenashev , the repo has now been successfully transferred. Happy to see it continue its life as a part of the Wiremock community!

**Comment by oleg-nenashev** [comment]
Thank you! Looking forward to improving it. If you are interested in continuing contributing to it or being a maintainer, you are more than welcome, and I will be happy to cooperate!

And thanks again for this project

**Comment by oleg-nenashev** [comment]
Hi @tyrjola just a heads-up I did the test 1.1.0 release after adding Pipelines. Looks good: https://pypi.org/manage/project/robotframework-wiremock/release/1.1.0/ . I will keep updating it before the next release
